In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [9]:
df = pd.read_csv('C:/Users/Admin/Desktop/project/전처리완료/20/01_전처리완료.csv', encoding='cp949')

In [10]:
# 대여 대여소명만 추출하고 중복 제거
rental_stations = df[['대여 대여소명']].drop_duplicates().copy()

print("2020년 1월 실제 이용된 대여소 수:", len(rental_stations))

rental_stations.head(20)

2020년 1월 실제 이용된 대여소 수: 1539

               대여 대여소명
0                 송도병원
1       KT 전화국 버스정류장 옆
2            삼부르네상스파크빌
3             대흥역 1번출구
4          마곡엠밸리10단지 앞
5            서울북부고용센터앞
6               원묵고등학교
7           서울 월드컵 경기장
8         천왕역 1번 출입구 앞
9          영등포구청역 7번출구
10          둔촌역 3번 출입구
11    한국전력공사(동대문 중랑지사)
12          신대방역 2번 출구
13        서울대입구역 마에스트로
14    건대입구역 사거리(롯데백화점)
15  생명의 전화 종합복지관 앞 교차로
16            삼전역 1번출구
18        서울시 도로환경관리센터
19          먹골역 6번출구 앞
20          성북구보건소 건너편

In [11]:
return_stations = df[['반납대여소명']].drop_duplicates().copy()

print("2020년 1월 실제 이용된 반납 대여소 수:", len(return_stations))

return_stations.head(20)

2020년 1월 실제 이용된 반납 대여소 수: 1539

                 반납대여소명
0            약수역 3번출구 뒤
1          중앙하이츠 아파트 입구
2             디지털입구 교차로
3              서강대 후문 옆
4                마곡역교차로
6            먹골역 1번출구 뒤
7                마포구청 앞
8             천왕지구삼거리 앞
9          양평동6차현대아파트 앞
10                강동세무서
11                장안중학교
12            신림동 우방아파트
13             봉천역 2번출구
14       자양사거리 광진아크로텔 앞
15                미아사거리
16               잠실근린공원
18             목동3단지 상가
19             중화역 2번출구
20           금호어울림센터힐 내
21  중계동 하나프라자빌딩 앞(중1-1)

In [12]:
all_stations = pd.concat([
    df[['대여 대여소명']].rename(columns={'대여 대여소명': '대여소명'}),
    df[['반납대여소명']].rename(columns={'반납대여소명': '대여소명'})
]).drop_duplicates()

print("2020년 1월 전체 대여/반납 대여소 수:", len(all_stations))

all_stations.head(20)

2020년 1월 전체 대여/반납 대여소 수: 1539

                  대여소명
0                 송도병원
1       KT 전화국 버스정류장 옆
2            삼부르네상스파크빌
3             대흥역 1번출구
4          마곡엠밸리10단지 앞
5            서울북부고용센터앞
6               원묵고등학교
7           서울 월드컵 경기장
8         천왕역 1번 출입구 앞
9          영등포구청역 7번출구
10          둔촌역 3번 출입구
11    한국전력공사(동대문 중랑지사)
12          신대방역 2번 출구
13        서울대입구역 마에스트로
14    건대입구역 사거리(롯데백화점)
15  생명의 전화 종합복지관 앞 교차로
16            삼전역 1번출구
18        서울시 도로환경관리센터
19          먹골역 6번출구 앞
20          성북구보건소 건너편

In [13]:
station_master = all_stations.copy()

station_master['자치구'] = None

In [14]:
print("대여소 개수:", len(station_master))
print(station_master.head(20))

대여소 개수: 1539
                  대여소명   자치구
0                 송도병원  None
1       KT 전화국 버스정류장 옆  None
2            삼부르네상스파크빌  None
3             대흥역 1번출구  None
4          마곡엠밸리10단지 앞  None
5            서울북부고용센터앞  None
6               원묵고등학교  None
7           서울 월드컵 경기장  None
8         천왕역 1번 출입구 앞  None
9          영등포구청역 7번출구  None
10          둔촌역 3번 출입구  None
11    한국전력공사(동대문 중랑지사)  None
12          신대방역 2번 출구  None
13        서울대입구역 마에스트로  None
14    건대입구역 사거리(롯데백화점)  None
15  생명의 전화 종합복지관 앞 교차로  None
16            삼전역 1번출구  None
18        서울시 도로환경관리센터  None
19          먹골역 6번출구 앞  None
20          성북구보건소 건너편  None

In [15]:
print(station_master.tail(20))

                      대여소명   자치구
31601        세곡사거리 대왕파출소 앞  None
31654         청담역(우리들병원 앞)  None
31841           내곡파출소 뒤 정자  None
32271        학동로 래미안 아파트 앞  None
32699        도곡동 경남아파트 건너편  None
33571          대륭테크노타운 18차  None
33963                 영남센터  None
36270             개화광역환승센터  None
42689      위례아이파크 101동 맞은편  None
48272   개포1단지아파트 입구 (보도육교)  None
55729              영동대교 북단  None
66784              서울혁신파크1  None
99328               탑성마을입구  None
104955           총신대 앞(육교)  None
108406           삼육대 제3과학관  None
201008     송파소방서 맞은편(성내4교)  None
243552              능안마을입구  None
277557                상암센터  None
494146                중랑센터  None
639353                개화센터  None

In [16]:
station_master = station_master.reset_index(drop=True)

print(station_master.shape)
station_master.head()

(1539, 2)

             대여소명   자치구
0            송도병원  None
1  KT 전화국 버스정류장 옆  None
2       삼부르네상스파크빌  None
3        대흥역 1번출구  None
4     마곡엠밸리10단지 앞  None

In [ ]:
station = pd.read_csv('C:/Users/Admin/Desktop/project/data/공공자전거 대여소 정보(26.6월 기준).CSV', encoding='cp949')
station = station.drop(['대여소\n번호', 'Unnamed: 3','Unnamed: 4', 'Unnamed: 5','설치\n시기', '설치형태', 'Unnamed: 8','운영\n방식', 'Unnamed: 10'],axis=1)
station.info()

<class 'pandas.DataFrame'>
RangeIndex: 2793 entries, 0 to 2792
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   보관소(대여소)명  2789 non-null   str
 1   소재지(위치)    2790 non-null   str
dtypes: str(2)
memory usage: 43.8 KB

In [28]:
station = station.iloc[4:]
station.head()

     보관소(대여소)명 소재지(위치)
4   망원역 1번출구 앞     마포구
5   망원역 2번출구 앞     마포구
6   합정역 1번출구 앞     마포구
7   합정역 5번출구 앞     마포구
8   합정역 7번출구 앞     마포구

In [29]:
station.to_csv(
    'C:/Users/Admin/Desktop/project/data/대여소정보.csv',
    index=False,
    encoding='cp949'
)

In [31]:
print(station.head())
print(station.columns)
print(station.shape)

     보관소(대여소)명 소재지(위치)
4   망원역 1번출구 앞     마포구
5   망원역 2번출구 앞     마포구
6   합정역 1번출구 앞     마포구
7   합정역 5번출구 앞     마포구
8   합정역 7번출구 앞     마포구
Index(['보관소(대여소)명', '소재지(위치)'], dtype='str')
(2789, 2)

In [32]:
station = station.rename(columns={
    '보관소(대여소)명': '대여 대여소명',
    '소재지(위치)': '자치구'
})

In [33]:
station.head()

       대여 대여소명  자치구
4   망원역 1번출구 앞  마포구
5   망원역 2번출구 앞  마포구
6   합정역 1번출구 앞  마포구
7   합정역 5번출구 앞  마포구
8   합정역 7번출구 앞  마포구

In [34]:
df = df.merge(
    station,
    on='대여 대여소명',
    how='left'
)

In [35]:
print("전체 데이터:", len(df))
print("자치구 매칭 성공:", df['자치구'].notna().sum())
print("자치구 매칭 실패:", df['자치구'].isna().sum())

전체 데이터: 789792
자치구 매칭 성공: 28302
자치구 매칭 실패: 761490

In [36]:
print(
    df.loc[df['자치구'].isna(), '대여 대여소명']
    .drop_duplicates()
    .to_list()
)

['송도병원', 'KT 전화국 버스정류장 옆', '삼부르네상스파크빌', '대흥역 1번출구', '마곡엠밸리10단지 앞', '서울북부고용센터앞', '원묵고등학교', '서울 월드컵 경기장', '천왕역 1번 출입구 앞', '영등포구청역 7번출구', '둔촌역 3번 출입구', '한국전력공사(동대문 중랑지사)', '신대방역 2번 출구', '서울대입구역 마에스트로', '건대입구역 사거리(롯데백화점)', '생명의 전화 종합복지관 앞 교차로', '삼전역 1번출구', '서울시 도로환경관리센터', '먹골역 6번출구 앞', '성북구보건소 건너편', '노원문화예술회관', '길음래미안아파트817동 상가 앞', '사근삼거리', '종로오가 지하쇼핑센터 14번출구', '한성대7번출구 앞', '자양(뚝섬한강공원)역 1번출구 앞', 'LIGA 아파트 앞', '잠실나루역 (2번 출구 쪽)', '가양역 8번출구', '수색역', '헬스케어', '엠펠리체 호텔 건너편', '금란주차장 앞', '서강대 정문 건너편', '석계역 문화광장 내 자전거 보관소', '곰달래사거리', '서울경찰청', '화곡역 1번 출구 앞', 'IFC몰', '돈암성당 옆', '성수아이에스비즈타워 앞', '삼익아파트', '독산근린공원 입구', '강일중,선사고 버스정류장(신암중학교 방면)', '홍남교 두바퀴쉼터', '쌍문동 이안아파트 앞', '백련산 힐스테이트 3차', '삼성생명 당산사옥 앞', '원일교회', '중랑세무서', '풍납현대아파트쉼터', '은천로입구 가로공원', '교대역 5번출구뒤', '석촌호수 아뜰리에', '왕십리역 4번 출구 건너편', '봉림교 교통섬', '올림픽공원 남2문 앞', '답십리초등학교 앞(현대시장 옆)', '강서구의회', '도림사거리', '홍은사거리', '더케이호텔 입구(양재2)', 'KB국민은행 염창역 지점 앞', '근로자회관 사거리', '현대6차 아파트', '길동 사거리(초소앞)', '용산 선인상가', '종로3가역 15번출구 뒤', '곰달래 문화복지센터 B', '장위뉴타운 꿈에 숲 코오롱 하늘채 앞', '조원동 강남힐병원', '은천초등학교 육교', '종로3가역 2번출구 뒤', '수연빌딩 앞', '서대문역 8번출구 앞', '여의나루역 1번출구 앞', '구로동롯데아파트', '3호선 매봉역 3번출구앞', '전농삼성아파트', '상봉역 3번출구', '동작경찰서', '성내어울터', '발산역 6번 출구 뒤', '도봉운전면허시험장 버스정류장 옆', '동원사거리', '성산2교 사거리', '성원2차 아파트', '서울시립대 건설공학관', '삼성광나루아파트 버스정류장', '외국어대 정문 앞', '노원경찰서교차로', '홈플러스 시흥점 맞은편 다비치안경 앞', '목동청소년수련관', '신도림2차e편한세상아파트 203동 앞', '서울혁신파크', '광진경찰서', '공항초등학교건너편', '구로도서관', '신길역3번출구', '군자역 7번출구뒤', '학여울역 사거리', '홈플러스 금천점 앞', '구의공원(테크노마트 앞)', '상계주공10단지 종합상가 앞', '태릉입구역 5번출구', '고덕역 4번출구', '강동구청 앞', '송정역 1번출구', '잠실새내역 5번 출구 뒤', '마포구민체육센터 앞', '서초4동주민센터', '홈플러스 면목동점', '신촌역(2호선) 1번출구 옆', '신림1교 교차로', '신동아아파트', '창동주공17단지 상가앞', '대치삼성아파트 앞 교차로', '신한은행 안국역지점 옆', '구일우성(아) 육교 밑', '연세대 정문 건너편', '연의근린공원 건너편', '대명초교 입구 교차로', '노원정보도서관', '샛마을 근린공원', '강서수도사업소민원센터', '강변역 4번출구 뒤', '동해문화예술관앞', '서울역사박물관 앞', '서울지방병무청 버스정류장', '중계역 3번출구', '아차산역 3번출구', '수협 연남동지점', '대청역 1번출구  뒤', '마곡13단지', '삼각산동 주민센터', '삼익세라믹아파트교차로', '성수2가1동 공영주차장 인근', '상월곡역 1번출구', '오목교역 7번출구 앞', '여의도역 1번출구 옆', 'KT혜화지사 앞', '그랜드컨벤션센터 앞', '가락시장역 3번 출구', '청계2가 사거리 옆', '목동3단지 상가', '대림사거리(동작상떼빌아파트)', '서울역 서부교차로2', '면목2동 사거리', '서울미래초등학교 사거리', '꿈돌이공원 앞', '롯데월드타워(잠실역2번출구 쪽)', '중앙하이츠 아파트 입구', '을지로입구역 4번출구 앞', '본 서부병원 버스정류장(은평 세무서 방면)', '노원역1번출구', '구로구청', '신설동역 11번출구 뒤', '강북구청 사거리 버스정류소 앞', '망원우체국사거리 인근', '모래내고가차도', '원메디타운 앞', '용답초등학교', '롯데캐슬엠파이어 옆', '대모산입구역 2번출구 앞', 'SK 서린빌딩 앞', '영동1교 (양재천근린공원)', '성수역3번출구', '불광롯데캐슬아파트 앞', '미성동 신림체육센터', '신영동삼거리(북악터널방향)', '중앙근린공원', '국민은행 종암동지점 앞', '용답역 1번 출구', '한신휴아파트 앞', '대학동 고시촌', '이태원관광특구입구A(녹사평역쪽)', '마곡나루역 5번출구 뒤편', '문래역 4번출구 앞', '상계동 우방유쉘아파트 앞', '양평1동 YP센터 앞', '불광역 8번출구', '동대문구민체육센터 (육교아래)', '서울보증보험본사 앞', '낙성대역 3번출구 뒤', '연신내역 6번출구옆', '센트럴 푸르지오 시티 앞', '송파나루역 4번 출구옆', '한진아파트 입구', '신방화역환승주차장', '방이초등학교', '광화문역 5번출구', '신자초교입구교차로', '종로4가 사거리', '삼양시장오거리', '강동세무서', '보라매 두산위브 건너편', '보문2교', '삼성역 3번 출구', '시립동부병원 앞 사거리', '마천사거리', '청담동 맥도날드 옆(위치)', '노량진역 5번출구', '천호초교 입구 사거리(일주빌딩)', '서울북부수도사업소', '진미파라곤 앞', '종로2가 버스정류장 (종각방향)', '원자력 병원', '을지로2가 사거리 북측', '양지근린공원앞', '옥수역 3번출구', '등촌역 7번출구', '봉천역 2번출구', '구 서부경찰서 건너편', '명동성당 앞', '송파여성문화회관 앞', '성수사거리 버스정류장 앞', '이수역 11번출구쪽', '은평평화공원(역촌역4번출구)', '석촌호수 서호 사거리', '맥스타일 앞', '청계천 박물관 앞', '탑골공원 앞', '압구정역 2번 출구 옆', '노원 구민회관', '신촌역(2호선) 7번출구 앞', '중랑구청 사거리', '암사역 3번출구(국민은행앞)', 'CJ 드림시티', '문정 법조단지10', '강동경찰서', '국회의사당역 3번출구 옆', '문정 법조단지8', '효성인텔리안 앞', '천호역4번출구(현대백화점)', '잠실주공 521동 건너편', '관악구 보건소', '석관초등학교 앞', '북가좌 초등학교', '합정역 5번출구 앞', '청량리 기업은행 앞', '홈플러스 신내점 앞', '독산역 2번출구 자전거주차장', '역삼서초삼성 세무서 앞 (역삼빌딩 앞)', '도봉구민회관', '대방역 4번출구', '개봉아이파크아파트 앞', '버스정류장 앞', '청운초교 앞 삼거리', '구일역 1번 출입구 앞', '장안동 사거리', '오류동역 맞은편', '논현역 10번출구', '문래동 하이테크 시티', '당산육갑문', '망원역 2번출구 앞', '교대입구 교차로', '중계근린공원내', '서울숲역 2번출구 앞', '솔밭공원역', '용마사거리', 'KT&G 관악지점', '문정중교 사거리', '먹골역 1번출구 뒤', '신당역 12번 출구 뒤', '혜명양로원 담장 옆', '밀리아나2빌딩 앞', '을지로입구역 2번출구', '고속터미널역 5번출구 앞', '대학로 마로니에공원', '하계2동 공항버스정류장 옆', '응암오거리', '광화문 시민열린마당', '망원역 1번출구 앞', '쌍용플레티넘오피스텔', '송리단길', '청계광장 옆', '마장동 주민센터', '정동사거리', '새솔초등학교', '성북제일새마을금고 본점 앞', '월곡역 입구 육교 밑', '등촌5단지아파트 버스정류장', '사당역 5번출구', '올림픽공원역 3번출구', '종암박스파크', '굽은다리역', '수유중앙시장', '디지털입구 교차로', '선릉역3번출구', '문정 법조단지9', 'DMC역 2번출구 옆', '419민주묘지역', '나들목공원', '왕십리 자이아파트(101동 앞)', '합정역 7번출구 앞', '당곡사거리', '다성이즈빌아파트(호원대 대각선 맞은편)', '명덕고교입구(영종빌딩)', '화양사거리', '수출의 다리 아래', '제일빌딩 앞', '도림천역 1번 출구 앞', '목동2단지 상가', '홍대입구역 8번출구 앞', '녹번역 3번출구', '동묘앞역 1번출구 뒤', '홍대입구역 2번출구 앞', '잠실근린공원', '시청역 1번출구 뒤', '청계벽산아파트 앞', '서우빌딩', '무지개아파트 앞', '구로거리공원 동측(신도림역 방면)', '우성아파트사거리 (기업은행앞)', '경서농협 버스정류장(우리은행신정동지점방향)', '연신내역 5번출구', '대림경동아파트앞', '청담나들목입구', '더라움', '북한산 우이역', '국민은행 연서지점', '구의문주차장 앞', '길음역 3번출구 뒤', '구파발역 2번출구', '석관동주민센터 앞', '광화문역 7번출구 앞', '독산고등학교', '고덕동 아남아파트', '북서울 꿈의 숲 동문', '여의도역 4번출구 옆', '포스코사거리(기업은행)', '서울시립대 정보기술관', '종로구청 옆', '송파역 2번 출구앞', '9955 도봉정비센터', '마포구청역', '합정역 1번출구 앞', '구산역 2번 출구 예일여고 버스정류장', '서강나루 공원', '중앙동 동진빌딩', '경복궁역 7번출구 앞', '안암로터리 버스정류장 앞', '문정현대아파트 교차로', '사천교', '청계천 한빛광장', '전농동 동아아파트 앞', '월계2교 버스정류장 앞', '자양사거리 광진아크로텔 앞', '서울본부세관(건설회관 앞)', '금옥여고보도육교', '잠실대교북단 교차로', '연희삼거리', '번동 주공3, 4단지 교차로', '강동 한신휴플러스', '동대문롯데캐슬아파트 앞', 'LG 사이언스파크', '경일중학교 앞', '극동늘푸른아파트', '수명중?고교', '상암월드컵파크 10단지 앞', '선린인터넷 고등학교', '노량진역 2번 출구 앞', '은평구청 보건소', '상암한화오벨리스크 1차 앞', '구의아리수정수센터앞', '독립문역 사거리', '동대문역 8번 출구', '명지전문대학교 정문 앞', '충정2교', '수서역 1번출구 앞', '쌍문현대1차아파트 108동 앞', '상봉역 1번출구', '방이동 한양3차아파트 옆', '하늘공원 입구', '샛강생태공원방문자센터 앞', 'SBS방송국', '송천동 주민센터', '신촌역(2호선) 6번출구 옆', '증산3교 앞', 'DMC파크뷰자이아파트 302동 앞', '공덕역 8번출구', '화랑대역 2번출구 앞', '래미안강남힐즈 사거리', '월드컵경기장역 3번출구 옆', 'KAIST 경영대학 앞', '중화역 2번출구', '용산전쟁기념관', 'LIG강촌아파트 103동앞', '위례중앙푸르지오 1단지 앞', '목동1단지아파트 118동 앞', '교보생명보험 앞', '서울역9번출구', '고척LIGA아파트 앞', '논현동 광명빌딩 앞', '노들역 1번출구', '도봉산역 교차로 앞', '꿈의숲 롯데캐슬', '신성기사식당 앞', '오목교역 3번출구', '래미안그레이튼102동앞', '건대입구역 5번출구 뒤', '벽산 디지털밸리 5차', '화랑대역 7번출구', '청파동입구 교차로', 'LG CNS앞', '거여역 8번출구 뒤', '한국우편사업진흥원', '사당동 아르테스 웨딩앞', '돈암초교 입구', '신도림역 1번 출구 앞', '태릉입구역 8번출구', '중랑교사거리', '코오롱테크노밸리', '양재시민의숲역 3번출구', '양지사거리', '신도림4차 e편한세상 아파트 1109동 앞', '광남중학교', '종합운동장역 4번출구', '상암월드컵파크 1단지 교차로', 'KEB은행 고대점', '석촌고분역 4번출구', '미아사거리', '중곡역 1번출구', '마장역 4번출구', '가락시장역 사거리', '삼각지역 3번출구', '자곡사거리', '조원동 미성아파트', '국회의사당역 5번출구 옆', '시범아파트버스정류장 옆', '홍연2교옆', '이대역 4번 출구', '올림픽공원역 1번출구 앞', '왕십리교회옆', '광산사거리', '신길우성1차아파트 앞 공원', '해뜨는 주유소옆 리엔파크 109동앞', '한사랑교회 앞', '보라매공원 보도육교', '한양대병원사거리', '풍납토성 서성벽터A', '영일 어린이공원', '서강대 후문 옆', '새절역 2번출구', '한울중학교', '보라매역?동작세무서 버스정류장(강남중학교방면)', '자양나들목', '도곡역 대치지구대 방향', '도봉한신아파트 버스정류장', '국민일보 앞', '개봉역 1번 출구 자전거보관서쪽', '신내능말공원', '온곡초교 교차로', '양문교회 앞', '시청역(2호선) 9번출구 뒤', '화곡역 버스정류장', '강동구청역 1번 출입구', 'KEB 하나금융그룹 명동사옥 옆', '몽촌토성역 1번출구 옆', '한남나들목 입구', '방학사거리 (봄마당 앞)', '문정 법조단지3', '석촌호수교차로(동호 팔각정 앞)', '연가초등학교 옆', '누리꿈스퀘어 옆', '성북3교 위', '잠실트리지움310동 옆', '광운대역 앞', '신이문역 1번출구', '장승배기역 5번출구', '신양초교앞 교차로', '신길동 우리은행 옆', '증산교 앞', '구의삼성쉐르빌 앞', '뚝섬 유원지역', '양평1나들목 보행통로 입구', '리센츠아파트', '마곡수명산파크3단지 교차로', '서울서초고용센터앞', '종묘공영주차장 건너편', '이수역 1번출구', '영등포로터리2', '이촌1동 마을공원', '초원아파트 앞', '강북구청사거리(수유역 8번출구)', '이태원지하보도', '커먼그라운드', '한성백제역 2번 출구', '볏골공원', '기자촌 사거리 A', '창동역 1번출구 건너편', '광진광장 교통섬', '청담역 2번출구', '고덕동 래미안 힐스테이트', '군자지하보도 앞', '대방역6번출구', '독산동 한양수자인아파트 앞', '노원역7번출구', '방이역 4번출구', '위례동주민센터', '효창공원앞역 3번출구 앞', '촬영소 사거리', '삼성역 8번출구', '남부고용노동지청 남측', '가좌역 4번출구 앞', '건국대학교 (입학정보관)', '홍익병원앞 교차로', '신설동역 10번출구 앞', '을지로2가 사거리 남측', '양재역 3번출구 주변', '동대문역사문화공원역 9번출구 앞', '약수역 3번출구 뒤', '수유2동은행빌딩 앞', '등촌9단지', '장안동위더스빌옆', '봉화산역 5번출구 뒤', '신림동주민센터', '백토공원 앞', '구룡마을 입구 (래미안블레스티지 아파트)', '역촌 센트레빌 아파트', '서교동 사거리', '곰달래 문화복지센터 A', '오륜사거리', '중랑전화국 교차로', 'W컨템포오피스텔앞', '오솔길공원', '사당역 7번출구쪽', '신용산역 6번출구 앞', '영파여고 앞', '신도림동주민센터 앞', '우리은행청량리지점앞', '천호역 10번 출구 앞', '마스타 빌딩 앞', '우장산역 3번출구', '효자동 삼거리', '장한평역 3번출구', '화곡역 6번출구', '월곡역 3번출구', '증산2교', '서대문구청', '중앙농협(자양동)', '신림동걷고싶은문화의거리입구', '고속터미널역 8-1번, 8-2번 출구 사이', '태릉입구역 3번출구', '서울시립과학관', '중계구민체육센터', '홍은동 정원여중 입구', '역촌파출소', '하늘채코오롱아파트 건너편', '방화역 4번출구앞', '우장산역 1번출구옆(우장산아이파크105동앞)', '청담역 13번 출구 앞', '신내우디안아파트 1단지', '목동사거리 버스정류장', '군자교교차로', '방화사거리 마을버스 버스정류장', '숭인2동 주민센터 입구', '마들역 7번출구', '신목동역 3번출구', '이마트 버스정류소 옆', '둔촌 주공 GS 맞은편', '서울역 12번 출구 앞', '마천중앙시장', '월드전기조명인테리어(우이동)', '길마중4교 하부', '도봉보건소사거리', '노량진근린공원 대방공원', '군자역2번출구', '번동 두산위브 101동 옆', '마곡역교차로', '영등포역지하쇼핑센타 5번출구', '중랑구청', '성동광진 교육지원청 앞', '상봉터미널2', '서울연신초등학교', '증산역 4번출구', 'DMC역 9번출구 앞', '충정로역 7번출구 아래', '압구정역 교차로', '미아동 복합청사', '남부터미널역 1번출구', '방학역사거리', '숙대입구역 8번', '신대방삼거리역 6번출구쪽', '개포동역 사거리', '서초역1번출구 앞', '500번,507번 버스 종점 앞', '문정 법조단지11', '미아역 3번,4번 출구 사이', '종로꽃시장 입구 옆', 'e편한세상 신촌4단지 앞', '방화동강서기동대앞', '고덕동 주양쇼핑', '양평우림 이비즈센타 앞', '한강진역 2번 출구 앞', '면목역 3번출구', '거여초등학교 옆', '홍은센트레빌 아파트 앞', '장충동먹자골목 앞', '서울북부지방법원', '답십리 래미안엘파인아파트 입구', '희성오피앙', '서울역 센트럴 자이아파트', '학동역', '원남동사거리', '남부법원검찰청 교차로', '영문초등학교 사거리', '인헌초교', '한마을아파트 정문상가', '북한산보국문역', '녹사평역1번출구', '목동1단지아파트 상가 앞', '삼성전자서비스 성북센터', '당고개공원 대여소', '이태원관광특구 입구(용산구청방향)', '발산역 1번, 9번 인근 대여소', '은평예술회관', '영등포구민체육센터 앞', '노일초등학교 앞', '대한항공 인력개발센터', '신도림테크노근린공원', '어린이회관', '청계천 영도교', '성산시영아파트', '명물길 원형무대 앞', '불광역 9번 출구', '보라매역4번출구', '장안동삼거리 교통섬', '금천폭포공원 앞', '신월중학교', '이촌1동 주민센터 뒤', '고려대학교 2번출구', '마곡역1번출구', '신당동주민센터앞', '신창시장', '송파소방서 (방이119안전센터)', '중곡사거리(국민은행)', '어린이대공원역 3번출구 앞', '서울특별시 은평병원', '해원리바파크 육교 밑', '세종사이버대학교', '영등포뉴타운지하상가 2번게이트', '연대 대운동장 옆', '상계주공2단지 버스정류장 옆', '강남한양수자인아파트', '세이브마트', '방학동우체국 건너편', '일진아이윌아파트 옆', '뚝섬역 1번 출구 옆', '북한산 코오롱 하늘채', '보라매역 8번출구', '미아사거리 1번 출구', '아차산역4번출구', '신길삼거리(우리은행)', '염창동 새마을금고 건너편', '도림신협 앞', '당산역 10번출구 앞', '대모산입구역 4번 출구 앞', '둔촌고교입구 교차로(길동주민센터 방면)', '오금역 3번 출구 뒤', '마포역 2번출구 뒤', '양천향교역 7번출구앞', '상계3,4동 주민센터 대여소', '세종대왕기념관 교차로', '남성역3번출구 뒤', '동성중학교 앞', '강서구청사거리(SH타워)', '중계역 6번출구', '응봉현대아파트 정류소', '군자역 7번출구 베스트샵 앞', '두산건설 본사', '수유1동 주민센터', '시조사 앞', '쌍문역4번출구 주변', '압구정파출소 앞', '증미역 3번출구뒤(등촌두산위브센티움오피스텔)', '신답역 사거리', '상봉시장앞 교차로 한성빌딩 앞', 'DMC빌 앞', '서울체육고등학교 앞', '동의보감타워', 'DMC홍보관', '신정3동 현장민원실 앞', '전농동 텃골공원', '독산보도육교 앞 자전거 보관소', '도봉역 1,2번 출구사이 건너편', '중곡 성원아파트 앞', '공릉역 1번 출구 앞', '롯데캐슬 앞', '개봉푸르지오아파트 상가', '관악동작견인차량보관소', '용두역 4번출구', '연희초등학교 앞', '극동방송국 앞', '래미안라센트아파트 103동 앞', '신도봉사거리 버스정류장', '공덕역 2번출구', '마들역 3번출구', '송파구청', '동양미래대학교 정문 옆', '연세로 명물길', '롯데캐슬골드파크1차 동문', '광나루역 3번 출구', '천일초교 사거리', '잣절보도육교 아래', '문래동자이아파트 앞', '서울대입구역 5번출구', '숙명여대 입구 교차로', '이마트 버스정류장(서부경찰서 방면)', '은평뉴타운구파발9단지', '봉은사역 5번출구 옆', '장승배기역2번출구뒷편쪽', '마곡엠밸리4단지 정문', '을지로3가역 3번출구', '시립미술관', '신한은행 대림동지점', '다산 어린이공원', '강월초교입구 사거리', '문정 법조단지7', '경희대학교 청운관', '사가정역 2번출구', '염창역 1번 출구', 'SPC 앞', '광진청소년수련관', 'K&S빌딩 앞', '역삼월드메르디앙아파트 앞', '한양대후문역 부근', '강일리버파크 2~5단지', '석촌역 2번출구', '용답토속공원 앞', '문정동 근린공원', '성균관대 E하우스 앞', '숭실대 입구역3번 출구 앞', '잠실역 6번출구', '현대벤처빌 앞', '가리봉동주민센터', '송파파인타운 7단지', '도림천 신화교', '석계역 5번출구 건너편', '봉은사로68길 북측', '동대문구 보건소', '신사동 가로수길 입구', '신촌기차역입구 교차로', '테라타워2', '삼성디지털프라자관악점', '응암1동사무소', '중화빌딩 앞 (동부시장)', '광흥창역 2번출구 앞', '도곡1동 주민센터 교차로', '문배어린이공원 앞', '방이역 1번출구', '숙대입구역 4번출구', '삼각지역 4번출구 앞', '마곡센트럴타워 1차', '수궁동 성당 주변', '신림역 8번출구', '역삼빌딩 앞(하나은행 옆)', '공릉1단지아파트', '삼성타운(삼성생명) A동 맞은편', '독립문역 3-1번출구', '홍제삼거리 북측', '장안중학교', '양재시민의숲역 1번출구', '현대고등학교 건너편', '구로리공원', '마곡엠밸리 15단지(1502동) 건너편', '중계동 하나프라자빌딩 앞(중1-1)', '서울신성초등학교', '가양3동 주민센터', '한내근린공원 남측', '서강대역 2번출구 앞', '해담는다리', '평생학습관 앞', '왕십리역 11번 출구 앞', '르네상스 호텔 사거리 역삼지하보도 7번출구 앞', '효창동주민센터 앞', '양재이스타빌 앞', '구일고등학교 정문', '노원역 5번출구', '등촌2동주민센터', '은평구청 교차로', '상아빌딩(우림시장 교차로)', '낙성대로 입구', '광운초등학교 앞', '당현천근린공원', '교보타워 버스정류장(신논현역 3번출구 후면)', '창동역 2번출구', '천왕연지타운2단지 앞', '해공공원(천호동)', '뚝섬역 5번 출구 정류소 옆', '송파구청 교차로', '유스호스텔 앞', '정릉도서관 앞', '중계중학교', '신내어울공원 앞', '미아동 한국전력공사', '삼양사거리역', '혜화동 로터리', '가좌역1 번출구 앞', '신월사거리', '하계동 중평어린이공원 앞', '관악구시설관리공단', '어린이대공원정문', 'KBS 스포츠월드', '아현역 4번출구 앞', '길음8골어린이공원 옆', 'KT선릉타워', '국립정신 건강센터 앞', '문정 법조단지5', '서울대입구역 1번출구', '성수역 2번출구 앞', 'KBS 앞', '광진교 남단 사거리(천호공원 방면)', '공항시장역 2번출구 뒤', '청담공원앞 교차로', '대륭포스트타워5차', '임광빌딩 앞', '망원1동주민센터', '흑석역 4번출구', '경희궁 자이 3단지', '서울출입국관리사무소 앞', '제일강산수산입구', '비전교회 앞', '응암시장교차로', '태평양물산', '가재울 초등학교', '성신여대입구 교차로', '역촌종합시장 버스정류장(예일여고 방면)', '신림역 5번출구', '군자교 서측 녹지대', '우성아파트 교차로', '목동3단지 시내버스정류장', '아시아지하보도 2번 출구', '거여동 사거리', '보라매공원 정문', '낙성대 과학전시관', '청계8가사거리 A', '한성대입구역2번출구', '기쁜우리복지관', '목동주차장', '유진투자증권빌딩 앞', '동작역 5번출구 동작주차공원', 'K+ 타워 앞', 'DMC첨단산업센터', '구산역 4번출구', '상월곡역 3번출구', '상암월드컵파크 3단지 후문', '삼성도로공원', '신용산역 1번 출구', 'DMC산학협력연구센터 앞', '등촌역 5번 출구 뒤', '상수역 2번출구 앞', '제기동역 1번출구', '한티역 3번출구', '혜화역 3번출구 뒤', '오금역 7번 출구 인근', '전자랜드 본관 앞', '서울혁신파크2', '창경궁 입구', '안국역 5번출구 앞', '코스트코 상봉점', '성서대학교 밀알관', '오목로 무중력지대 앞', '중계종합사회복지관 교차로', '마천금호어울림 1차아파트 건너편', '석촌호수교차로 (송파나루근린공원 앞)', '신대방삼거리역 3번출구쪽', '난곡종점', '충무로역 1번출구', 'MCM 본사 직영점 앞', '등촌2파출소', '낙성대역 1번출구', '훈련원공원주차장 앞', '주식회사 오뚜기 정문 앞', '신도고등학교', '천주교 대치 2동 교회 옆', '삼환로즈빌아파트 105동 옆', '대림아파트 사거리', '창신역 1번출구 앞', '이앤씨드림타워 앞', '명지대학교 도서관', '강일동 리슈빌 빌딩앞', '화곡본동시장 버스정류장', '양평동6차현대아파트 앞', '금호어울림센터힐 내', '한국SGI 양천문화회관 앞', '영도초등학교', '용문사 버스정류장', '9호선종합운동장역 9번출구', '래미안 강동팰리스(102동)', '무악재역1번 출구', '신촌동 제1공영주차장 앞', 'KT앞', '가락미륭아파트 앞', '일신초등학교 옆', '신길선원가와인아파트 앞', '금원빌딩 앞', '가락고등학교 앞', '송파체육문화회관 앞', '광진메디칼 앞', '난우길입구', '상왕십리역 4번 출구 앞', '구로디지털단지역 앞', '롯데캐슬 102동 코너(월계주유소건너)', '월드메르디앙 벤처센터 2차', '목동사거리 부근', '동대문 종합시장 버스정류장', '프라자 아파트 앞', '인덕대학교', '청솔우성아파트 앞', '강서구보건소', '건국대학교 학생회관', '수서역 5번출구', '남영역 건너편', '북가좌1동 주민센터', '대치역 사거리', '강북중학교 앞', '신정3동주민센터', '겸재교 진입부', '장수공원', '반포본동 주민센터 앞', '도봉구청 정문앞', '영휘원 교차로', '신설동역8번출구', '포스코사거리 서측(수협 삼성동 지점)', '정릉역', '과기대 입구(우)', '답십리역 1번출구', '대흥동 주민센터', '서초유치원 맞은편', '양녕로 입구', '서빙고동 주민센터 앞', '래미안금호하이리버 아파트 102동 옆', '청계7가 사거리', '위례송파꿈에그린아파트24단지 앞 성벽 다리 밑', '신풍역 5번출구 인근', '상봉역 2번 출구', '고려사대부속중고 건너편', '풍납토성 서성벽터B', '신림동 우방아파트', '대림역4번출구', '신방화사거리', '서남환경공원 버스정류장', '여의도초교 앞', '서부식자재마트 건너편', '강서초등학교', '개봉역2번출구 A', '경기여자고등학교 후문 (삼성로3길 입구)', '역삼동 디오슈페리움 (우성아파트 사거리)', '복정역 2번출구 후문 (장지치안센터)', '성산2-1 공영주차장', '서강대 남문 옆', '용두동 래미안허브리츠아파트 앞', '면목4치안센터', '등촌역 1번출구옆', '롯데캐슬 115동앞', '광화문 S타워 앞', '언남초등학교 앞', '행당역 2번출구 앞', '용산중학교', '신림푸르지오아파트', '길음문화복합미디어센터', '흑석역 1번출구', '남구로역 5번 출입구 앞', '대림아크로리버 앞', '삼양역', '연신내역 4번출구', '북서울 꿈의숲 서문', '고척근린공원 고척도서관 앞', '서초리슈빌S 글로벌 앞', '강북종합시장 앞', '목월공원 앞', '미아역 1번 출구 뒤', '말죽거리공원 사거리', '장미원시장 건너편', '광진문화예술회관 앞', '천왕역 4번출구 뒤', '뱅뱅사거리 랜드마크타워 앞', '송파지역자활센터 뒤', '광화문역 2번출구 앞', '바우뫼문화복지회관', '가산동 주민센터', '상암월드컵파크 7단지 앞', '강서구청사거리(부민병원)', '방학동학마을도서관', '보아스아파트 앞', '한강 현대아파트 건너편', '금호스포츠센터앞', '용마한신아파트사거리', '염창동 한마음아파트 앞', '전농사거리 교통섬', '동아1차APT105동 버스정류장(신도림중학교 방면)', '거여역 3번출구', '마곡 엠밸리2단지', '청계천 생태교실 앞', '장한평역 8번 출구 앞', '강남구청', '영등포삼환아파트 앞', '보광동 삼성리버빌아파트 앞', '노원구청', '유니베라 앞', '강남구 도시관리공단', '두상빌딩 앞', '아주중학교건너편', '서빙고동 금호맨션 앞', '진주아파트상가 앞', '신정네거리역', '응봉삼거리', '부엉이공원 앞', '보문역6번출구 앞', '중랑구청 중화동 별관 앞', '강서구립등빛도서관', '용강동 주민센터 앞', '모두의학교', '불광역 2번출구', '영등포청과시장 사거리', '잠실역 8번출구', '문화촌 공원', '삼일초등학교 인근', '삼청동 골목', '내곡3단지 어린이공원 앞', '서울시립대 후문', '마포소방서 앞', '국군복지단', '포레스 주상복합 빌딩', '금호 어울림 아파트 앞', '삼전역 4번출구', '현대6차아파트 101동 옆', '마포 신수공원 앞', '영등포전화국사거리 (서강어린이공원)', '구립망우청소년독서실', '으뜸공원', '노원소방서인근', '목4동주민센터 옆', '동원베네스트 건물 앞', '신정이펜하우스314동', '(구)합정동 주민센터', '아리랑시네센터 앞', '예일여중', '선유도역 3번출구 앞', '삼호아파트 2동 ( 간선도로)', '마포구 육아종합지원센터', '창1동주민센터', '종각역 1번출구 앞', '올림픽기념 국민생활관 앞', '은평뉴타운 상림마을 13단지', '디지털미디어 시티역 4번출구(DMC역)', '양평1 보행육교 앞', '신수동 사거리', '삼부아파트1동 앞', '상암중학교 옆', '한내근린공원 북측', '송파파크데일 2단지입구 앞 주차장', '우이동길마을마당', '상암월드컵파크 9단지 앞', '마곡역 버스정류장(마곡나루역1번출구, 웰튼병원 방면)', '아크로타워 스퀘어(영등포시장)', '문정 법조단지4', '신당 래미안 버스정류장', '은천치안센터', '보문4교 인근', '북한산힐스테이트 7차아파트', '동방1교', '장지공영차고지', '해공도서관앞', '마포구청 앞', '잠실나들목', '녹천역 1번출구 앞', '봉원고가차도 밑', '대현그린타워', '신목동역 2번 출구', '답십리역 8번출구 앞', '샛강역 1번출구 앞', '삼성전자 물류센터 앞', '마곡중학교 후문', '마곡수명산파크 209동 건너편', '한전아트센터 앞', '상림마을 생태공원', '중계동 을지중학교', '면목 대원칸타빌아파트', '충북 미래관', '증권거래소 앞', '왕십리자이아파트 후문(삼거리)', '센서텍㈜', '한신코아 앞', '서울시 품질시험소 앞', '공무원연금매점 교차로 (개포주공9단지 입구)', '구암초등학교 버스정류장', '복자사랑 피정의 집', '서울대학교 정문', '강서구청', '고척교 교차로', '가락삼환아파트 앞', '응봉역 1번출구', '서울산업정보학교', '독립문 어린이 공원', '청구 어린이공원', '참새공원(백곡경노당)', '경복궁역 6번출구 뒤', '신내역 4번출구', '서울반도체고 앞', '양재역 10번 출구 앞', '독산주공 14단지 버스정류소', '정릉꿈에그린1단지 201동 앞', '연서어린이공원', '중곡SK아파트앞', '목동11단지 아파트', '잠원역 3번-4번 출구사이', '상월곡역 4번출구', '월드컵공원', '반포1동 서초빌딩 앞', 'e 편한세상 보문아파트 내', '동작구민 체육센터', '황금내근린공원', '독바위역', '용두동 사거리', '일원역 4~5번 출구 사이', '방화근린공원', '도봉고등학교 맞은편', '은평 지웰테라스', '서울시 공공자전거 상암센터', '앙카라공원 앞', '북가좌 삼거리', '답십리초등학교 옆 공원', '국립현대미술관', '구룡터널 입구(개포1단지아파트)', '서울 시흥동우체국 앞', '역삼동 sk뷰 501동앞', '용마산역 1번출구', '마포중앙도서관', '마포역 4번출구 뒤', '강서수산물도매시장', '구파발역 환승센터', '을지로4가역 1번출구', '망원2빗물펌프장 앞', '상도역 1번출구', '양서중학교 옆', '도봉구청 옆(중랑천변)', '오류동역 2번출구', '여의도고교 앞', '잠실3거리(갤러리아팰리스)', '충무로역 6번출구 앞', '동아에코빌입구', '가양레포츠센터 앞', '약수역 10번출구 앞', '선사고등학교', '사육신공원앞', '서초구립반포도서관 앞', '마포어린이공원', '연희교차로 인근', '은평뉴타운 도서관', '국회의원회관', '국립국악중,고교 정문 맞은편', '홍익중고 입구', '금천구청 앞 자전거거치대', '서초포레스타 7단지', '서초신동아1차아파트 옆', '이수역 6번출구 앞', '마곡역 교차로(2번출구)', 'JK장평타워', '청계산입구역 2번출구', '서울특별시교육청도봉도서관', '삼호물산버스정류장(23370) 옆', '공항중학교앞', '아차산 휴먼시아 아파트 옆', '신정이펜하우스 1단지아파트 입구 사거리', 'LH서초3단지 301동 맞은편', '신사동 성당', '신트리공원 입구', '늘푸른공원 앞', 'LG베스트샵 종암점', '서울숲역 5번 출구 옆', '서울서부지방법원 앞', '에이스에이존빌딩', '용문2교 옆', '낙원상가 옆', '제기2교', '농수산식품공사 (강서지사)', '번3동 주민센터 교차로', '한신16차아파트 119동 앞', '상일초등학교', '개봉지구대 개봉치안센터', '문정 법조단지6', '잔디마을 마을버스 정류장', '구의3동주민센터', '둔촌어린이공원', '방배래미안 정문 앞', '마곡엠밸리6_7단지 마곡중학교', '유한양행앞', '고척스카이돔구장 광장', '내방역 8번출구 앞', '은평뉴타운 아이파크', '고덕숲 아이파크 2', '서울여대 남문', '한남초교 앞 보도육교', '리싸이클시티', '대림3동사거리', '영등포유통상가 사거리', '개화산역 2번 출구', '번동주공5단지 관리사무소 앞', '상계동수락리버시티', '애오개역 4번출구 앞', '대원중고교 입구(대하빌딩)', '한남 유수지 복개주차장', '안암2교 옆', '서울시설공단 앞', '제2구민체육센타 앞', '서래마을파리15구공원앞', '르네상스호텔사거리 역삼지하보도 3번출구 앞 (더 오번 빌딩 명동칼국수 앞)', '송정중학교', '서울강월초등학교 앞', '구로역 광장', '서울숲 IT캐슬', '주홍교 하부', '포르투갈 대사관 앞', '대림역 1번 출입구 밑', '올림픽로 836(아리수로)', '종각역 5번출구', '서초 포레스타5단지', '관악구청교차로', '광양중학교 앞', '고려사대부속중고 정문', '흑석한강푸르지오 106동앞', '북성초교', '금융감독원 앞', '신일해피트리아파트 앞', '경희궁 자이 2단지', '주공14단지', 'JW타워', '현대자동차서비스 앞', '삼성화재 사옥 옆', '강동구평생학습관앞', '현대홈타운 뒷길', '구로중학교앞', '오금공원 사거리', '관악우체국', '안골마을입구', '문화비축기지', '신이문역 2번출구', '묘곡초등학교', '불암고등학교 앞 횡단보도', '휘경2동 주민센터', '송파도서관', '세종대학교 대양AI센터', '옥수동성당 옆', 'SK 남산빌딩', '광화문역 1번출구 앞', '만해공원', '이수센터', '서울신용보증재단', '육군사관학교  앞', '그룹한빌딩옆', '서초역 3번출구', '한신아파트 앞 육교 아래', '송파중학교 정문', '금암 문화공원', '강일리버파크 6단지', '연신내역 3번출구 인근', '성북동 치안센터 앞', '성수아카데미타워 앞', '쌍용예가(구청별관)', '휘봉고등학교 앞', '상왕십리역 1번출구', '문정동 글샘 공원', '온수역 북측', 'LG유플러스 (방배사옥)', '연신내 선일하이츠빌 정류소', '이대역 5번출구', '미성아파트 A동 앞', '롯데하이마트 (상암월드컵점)', '성동세무서 건너편', '건국대학교 (행정관)', '서울시여성가족재단', '재동초교 앞 삼거리', '은평역사한옥박물관', '이촌2동 동원베네스트 아파트 앞', '잠실4동 주민센터 옆', '보성중고등학교 후문 앞', '구룡초사거리 (현대아파트10동 앞 )', 'NH농협은행 앞', '동대문경찰서 교차로', '오리로와 서해안도로 교차로 앞', '메뚜기다리', '구룡사 앞 교차로 (보도육교)', '이대목동병원보도육교', '능골근린공원', '동대문중 교차로', '은평뉴타운 힐데스하임', '동일로 지하차도', '도봉문화정보도서관 삼거리', '성동세무서 부근', '동대입구역 6번출구 뒤', '도선동 주민센터 앞', '롯데캐슬골드파크1차 서문', '이수고가차도 남단', '대륭포스트타워1차', '달맞이공원', '한국종합기술사옥 앞', '면목도시개발아파트 1동 앞', '여의도중학교 옆', '심산기념문화센터', '갑을그레이트밸리 앞', '왕십리KCC스위첸아파트', '오정초교 앞 보도육교', '솔브레인이엔지 뒤편', '보금자리정원', '포스코피앤에스타워 (역삼역 3번출구 부근)', '동명근린공원 진입로 (아리수로)', '성북구청', '파르코 앞', '서울연신중학교', '서울숲 관리사무소', '솔샘역 2번 출구', '송천동우체국', '여의도 마리나선착장 앞', '연신내역 1번 출구', '현대아파트 정문 앞', '망우역 1번출구', '금천구립 독산도서관', '말우물 어린이 공원', '강북문화예술회관', '반포종합운동장 입구', 'CJ제일제당 앞', '면목초등학교', '금호역 1번출구 앞', '공덕역 5번출구', '양강중학교앞 교차로', '세곡동 성당', '언주역 4번출구', '장충체육관', '삼성역 5~6번 출구 사이', '번동 금호어울림아파트102동앞', '신세계백화점 본점 앞', '금호역 3번출구', '고덕초등학교', '압구정 한양 3차 아파트', '서남물재생센터 버스정류장', '정금마을 마을버스정류장', '삼육대 도서관', '중앙대학교 정문 1', '계남공원 입구 주출입구 좌측', '청와대앞길', '롯데중앙연구소', '구로1동우체국 앞', '용신동주민센터', '가오리역', '방배래미안아트힐 101동앞', '빅마켓 금천점 앞', '서울교통공사 사당별관 건너편', '성북쉼터 앞', '미호 플랜트 앞', '신사역 4번출구 뒤', '은평뉴타운 푸르지오', '서서울모터리움 앞', '종로6가역 버스정류장(동대문 방향)', '우솔초등학교 맞은편', '신한은행 시흥대로금융센터지점', '용마지구대 A', '방일초교 마을버스 정류장', '노해근린공원내', '구파발10단지 인근', '진관동 은빛초등학교', '가산아네스트 오피스텔 앞', '염곡치안센터 건너편', '중림동삼거리', '영어마을 관악캠프', '위례별 유치원 뒤', '수서역 7번출구 앞', '코오롱One&Only타워', '강일리버파크 7~11단지', '논골사거리(금호도서관 입구)', '중랑캠핑숲', '청계산 입구 삼거리', '두산위브아파트 옆 상가건물 앞', '금호사거리', '영동3교 북단(우성캐릭터 앞 보도)', '강서대학교', '광교사거리 남측', 'CJ오쇼핑앞', '강남세브란스교차로  래미안그레이튼 104동 앞', '망원초록길 입구', '성지아파트 옆 도로변', '강남구청역 2번출구 뒤', '서울디지털운동장 앞', '송파 글마루 도서관', '상도 아이파크 아파트', '서울식물원(문화센터) 건너편', '한국전력 구로금천지사 앞', '밀알학교 입구 (삼성서울병원 입구)', '일동제약 사거리', '한국과학기술연구원 중문', '리엔파크 2단지 앞', '광화문역 6번출구 옆 B', '한성대입구역6번출구 뒤', '서원마을', '미림여고입구 교차로', '동인오피스텔 건너편 소공원', '신반포역 2번출구 앞', '목동운동장', 'STX V타워', '본마을 정류소 앞', '세종대학교(학술정보원)', '이화여대 후문', '삼성중앙역4번출구(문화센터더 리빌)', '비계 버스정류소', '선잠단지 앞', '금강수목원아파트 앞', '용산 파크타워 앞', '산업은행 앞', '삼청공원 앞', '대치동 삼성로', '사당중학교 버스정류소', '공항시장역 4번출구', '상암동주민센터 옆', '천왕이펜하우스 4단지 후문', '동영문화센터앞', '강서면허시험장 앞', '대림아파트 후문 상가 옆', '구룡산 입구 (구룡산 서울둘레길 입구)', '반포1동 주민센터 앞', '건국대학교 과학관(이과대) 앞', '청년취업사관학교앞', '구로구배드민턴실내체육관 앞', '강일리버파크 10단지', '증권거래소후문교차로', '중앙고입구 삼거리', '도산공원교차로', '일성아파트', '명보사거리', '에이스하이엔드타워9차 앞', '중랑물재생센터(서울새활용플라자)', '금남시장 교차로', '청소년수련관(수영장)앞', '동작역 7번출구', '강북구청 뒷편', '도봉산광역환승센터앞', '시립창동운동장 입구',