In [89]:
# # 대여소명 정리
# df['대여소명'] = df['대여소명'].apply(lambda x: x.split('.')[1].strip())
# df

In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

In [2]:
import pandas as pd

In [113]:
# 파일 경로 이름 줄이기 / 년도 폴더 가져오기
path = r'C:\ai\Source\09_Project\01_Data\서울특별시_대여소별 공공자전거 대여가능 수량(1시간 단위)\2025년'

# 월 파일 읽어들이기
df = pd.read_csv(f'{path}/data_2512.csv', encoding='cp949')
df

                 일시  대여소번호                   대여소명  시간대  거치대수량
0        2025-12-01    102        102. 망원역 1번출구 앞    0      8
1        2025-12-01    103        103. 망원역 2번출구 앞    0     21
2        2025-12-01    104        104. 합정역 1번출구 앞    0     13
3        2025-12-01    105        105. 합정역 5번출구 앞    0      5
4        2025-12-01    106        106. 합정역 7번출구 앞    0     10
...             ...    ...                    ...  ...    ...
2076126  2025-12-31   6185             6185.가양나들목   23      8
2076127  2025-12-31   6187     6187.마곡119안전센터 맞은편   23      3
2076128  2025-12-31   6188             6188.금호아파트   23     28
2076129  2025-12-31   6189     6189.데시앙플렉스 지식산업센터   23     10
2076130  2025-12-31   6190  6190.마곡광장(마곡나루역 6번출구)   23      3

[2076131 rows x 5 columns]

In [114]:
# 전체 행렬 확인
df.shape

(2076131, 5)

In [115]:
# '대여소 번호' 컬럼 삭제
df.drop('대여소번호', axis=1, inplace=True)

In [116]:
# 전체 행렬 확인
df.shape

(2076131, 4)

In [117]:
df.dtypes

일시       object
대여소명     object
시간대       int64
거치대수량     int64
dtype: object

In [118]:
# 일시_datetime의로 유형 변경
df['일시'] = pd.to_datetime(df['일시'], format='%Y-%m-%d');
df.dtypes

일시       datetime64[ns]
대여소명             object
시간대               int64
거치대수량             int64
dtype: object

In [119]:
# 거치대 수량 결측치 확인
(df['거치대수량'] < 0).sum()

0

In [120]:
# 요일 추가하기
df['요일'] = df['일시'].dt.dayofweek
df

                일시                   대여소명  시간대  거치대수량  요일
0       2025-12-01        102. 망원역 1번출구 앞    0      8   0
1       2025-12-01        103. 망원역 2번출구 앞    0     21   0
2       2025-12-01        104. 합정역 1번출구 앞    0     13   0
3       2025-12-01        105. 합정역 5번출구 앞    0      5   0
4       2025-12-01        106. 합정역 7번출구 앞    0     10   0
...            ...                    ...  ...    ...  ..
2076126 2025-12-31             6185.가양나들목   23      8   2
2076127 2025-12-31     6187.마곡119안전센터 맞은편   23      3   2
2076128 2025-12-31             6188.금호아파트   23     28   2
2076129 2025-12-31     6189.데시앙플렉스 지식산업센터   23     10   2
2076130 2025-12-31  6190.마곡광장(마곡나루역 6번출구)   23      3   2

[2076131 rows x 5 columns]

In [121]:
# 요일 위치 변경
df = df[['일시', '요일','시간대', '대여소명', '거치대수량']]
df

                일시  요일  시간대                   대여소명  거치대수량
0       2025-12-01   0    0        102. 망원역 1번출구 앞      8
1       2025-12-01   0    0        103. 망원역 2번출구 앞     21
2       2025-12-01   0    0        104. 합정역 1번출구 앞     13
3       2025-12-01   0    0        105. 합정역 5번출구 앞      5
4       2025-12-01   0    0        106. 합정역 7번출구 앞     10
...            ...  ..  ...                    ...    ...
2076126 2025-12-31   2   23             6185.가양나들목      8
2076127 2025-12-31   2   23     6187.마곡119안전센터 맞은편      3
2076128 2025-12-31   2   23             6188.금호아파트     28
2076129 2025-12-31   2   23     6189.데시앙플렉스 지식산업센터     10
2076130 2025-12-31   2   23  6190.마곡광장(마곡나루역 6번출구)      3

[2076131 rows x 5 columns]

In [122]:
# 파일 저장
df.to_csv('Cleaned/2025_Prep/2025.12_Prep-utf8.csv', encoding = 'utf-8-sig', index = False)