In [21]:
# # 대여소명 정리
# df['대여소명'] = df['대여소명'].apply(lambda x: x.split('.')[1].strip())
# df

In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:85% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

In [2]:
import pandas as pd
import glob

In [124]:
# 파일 경로 이름 줄이기 / 년 폴더 불러들이기
path = r'C:\ai\Source\09_Project\01_Data\서울특별시_대여소별 공공자전거 대여가능 수량(1시간 단위)\2023년'

# 컬럼 이름 변경
columns = ['일시', '대여소번호', '대여소명', '시간대', '거치대수량']

# 월 폴더 가져오기
file1 = f'{path}/data_231201~231215.csv'
file2 = f'{path}/data_231216~231231.csv'

df1 = pd.read_csv(file1, encoding='cp949', header=None, names=columns)
df2 = pd.read_csv(file2, encoding='cp949', header=None, names=columns)

# 두 데이터프레임 병합
df = pd.concat([df1, df2], ignore_index=True)
df

                  일시  대여소번호                    대여소명  시간대  거치대수량
0         2023-12-01    102         102. 망원역 1번출구 앞    0     30
1         2023-12-01    103         103. 망원역 2번출구 앞    0     21
2         2023-12-01    104         104. 합정역 1번출구 앞    0      8
3         2023-12-01    105         105. 합정역 5번출구 앞    0     15
4         2023-12-01    106         106. 합정역 7번출구 앞    0      2
...              ...    ...                     ...  ...    ...
12128996  2023-12-31   6053           6053. 중부세무서 앞   23      0
12128997  2023-12-31   6054  6054.청구e편한세상아파트 113동 앞   23      5
12128998  2023-12-31   6055              6055. 한국경제   23     12
12128999  2023-12-31   6171            6171. 월드빌딩 앞   23      0
12129000  2023-12-31   6172          6172. 가양5단지아파트   23      9

[12129001 rows x 5 columns]

In [125]:
# 전체 행렬 확인
df.shape

(12129001, 5)

In [126]:
# '대여소 번호' 컬럼 삭제
df.drop('대여소번호', axis=1, inplace=True)

In [127]:
# 전체 행렬 확인
df.shape

(12129001, 4)

In [128]:
df.dtypes

일시       object
대여소명     object
시간대       int64
거치대수량     int64
dtype: object

In [129]:
# 일시_datetime의로 유형 변경
df['일시'] = pd.to_datetime(df['일시'], format='%Y-%m-%d')
df.dtypes

일시       datetime64[ns]
대여소명             object
시간대               int64
거치대수량             int64
dtype: object

In [130]:
# 데이터 정렬 (일시 오름차순 -> 시간대 오름차순 순서로 정렬)
df = df.sort_values(by=['일시', '시간대'], ascending=[True, True])

# 정렬 후 뒤섞인 인덱스를 0부터 다시 깔끔하게 초기화
df = df.reset_index(drop=True)

In [131]:
# 거치대 수량 결측치 확인
(df['거치대수량'] < 0).sum()

0

In [132]:
# 요일 추가하기
df['요일'] = df['일시'].dt.dayofweek
df

                 일시                    대여소명  시간대  거치대수량  요일
0        2023-12-01         102. 망원역 1번출구 앞    0     30   4
1        2023-12-01         103. 망원역 2번출구 앞    0     21   4
2        2023-12-01         104. 합정역 1번출구 앞    0      8   4
3        2023-12-01         105. 합정역 5번출구 앞    0     15   4
4        2023-12-01         106. 합정역 7번출구 앞    0      2   4
...             ...                     ...  ...    ...  ..
12128996 2023-12-31           6053. 중부세무서 앞   23      0   6
12128997 2023-12-31  6054.청구e편한세상아파트 113동 앞   23      5   6
12128998 2023-12-31              6055. 한국경제   23     12   6
12128999 2023-12-31            6171. 월드빌딩 앞   23      0   6
12129000 2023-12-31          6172. 가양5단지아파트   23      9   6

[12129001 rows x 5 columns]

In [133]:
# 요일 위치 변경
df = df[['일시', '요일','시간대', '대여소명', '거치대수량']]
df

                 일시  요일  시간대                    대여소명  거치대수량
0        2023-12-01   4    0         102. 망원역 1번출구 앞     30
1        2023-12-01   4    0         103. 망원역 2번출구 앞     21
2        2023-12-01   4    0         104. 합정역 1번출구 앞      8
3        2023-12-01   4    0         105. 합정역 5번출구 앞     15
4        2023-12-01   4    0         106. 합정역 7번출구 앞      2
...             ...  ..  ...                     ...    ...
12128996 2023-12-31   6   23           6053. 중부세무서 앞      0
12128997 2023-12-31   6   23  6054.청구e편한세상아파트 113동 앞      5
12128998 2023-12-31   6   23              6055. 한국경제     12
12128999 2023-12-31   6   23            6171. 월드빌딩 앞      0
12129000 2023-12-31   6   23          6172. 가양5단지아파트      9

[12129001 rows x 5 columns]

In [134]:
# 파일 저장
df.to_csv('Cleaned/2023_Prep/2023.12_Prep-utf8.csv', encoding = 'utf-8-sig', index = False)